// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import (
	model "github.com/nschimek/nice-fixture-service/model"
	rest_error "github.com/nschimek/nice-fixture-service/model/rest_error"
	mock "github.com/stretchr/testify/mock"
)

// League is an autogenerated mock type for the League type
type League struct {
	mock.Mock
}

type League_Expecter struct {
	mock *mock.Mock
}

func (_m *League) EXPECT() *League_Expecter {
	return &League_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function with given fields: id
func (_m *League) GetById(id int) (*model.League, *rest_error.Error) {
	ret := _m.Called(id)

	var r0 *model.League
	var r1 *rest_error.Error
	if rf, ok := ret.Get(0).(func(int) (*model.League, *rest_error.Error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.League); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.League)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *rest_error.Error); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*rest_error.Error)
		}
	}

	return r0, r1
}

// League_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type League_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - id int
func (_e *League_Expecter) GetById(id interface{}) *League_GetById_Call {
	return &League_GetById_Call{Call: _e.mock.On("GetById", id)}
}

func (_c *League_GetById_Call) Run(run func(id int)) *League_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *League_GetById_Call) Return(_a0 *model.League, _a1 *rest_error.Error) *League_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *League_GetById_Call) RunAndReturn(run func(int) (*model.League, *rest_error.Error)) *League_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByParams provides a mock function with given fields: params
func (_m *League) GetByParams(params model.LeagueParams) ([]model.League, *rest_error.Error) {
	ret := _m.Called(params)

	var r0 []model.League
	var r1 *rest_error.Error
	if rf, ok := ret.Get(0).(func(model.LeagueParams) ([]model.League, *rest_error.Error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(model.LeagueParams) []model.League); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.League)
		}
	}

	if rf, ok := ret.Get(1).(func(model.LeagueParams) *rest_error.Error); ok {
		r1 = rf(params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*rest_error.Error)
		}
	}

	return r0, r1
}

// League_GetByParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByParams'
type League_GetByParams_Call struct {
	*mock.Call
}

// GetByParams is a helper method to define mock.On call
//   - params model.LeagueParams
func (_e *League_Expecter) GetByParams(params interface{}) *League_GetByParams_Call {
	return &League_GetByParams_Call{Call: _e.mock.On("GetByParams", params)}
}

func (_c *League_GetByParams_Call) Run(run func(params model.LeagueParams)) *League_GetByParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.LeagueParams))
	})
	return _c
}

func (_c *League_GetByParams_Call) Return(_a0 []model.League, _a1 *rest_error.Error) *League_GetByParams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *League_GetByParams_Call) RunAndReturn(run func(model.LeagueParams) ([]model.League, *rest_error.Error)) *League_GetByParams_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewLeague interface {
	mock.TestingT
	Cleanup(func())
}

// NewLeague creates a new instance of League. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLeague(t mockConstructorTestingTNewLeague) *League {
	mock := &League{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
