// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import (
	model "github.com/nschimek/nice-fixture-service/model"
	rest_error "github.com/nschimek/nice-fixture-service/model/rest_error"
	mock "github.com/stretchr/testify/mock"
)

// Team is an autogenerated mock type for the Team type
type Team struct {
	mock.Mock
}

type Team_Expecter struct {
	mock *mock.Mock
}

func (_m *Team) EXPECT() *Team_Expecter {
	return &Team_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function with given fields: id
func (_m *Team) GetById(id int) (*model.Team, *rest_error.Error) {
	ret := _m.Called(id)

	var r0 *model.Team
	var r1 *rest_error.Error
	if rf, ok := ret.Get(0).(func(int) (*model.Team, *rest_error.Error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *model.Team); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *rest_error.Error); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*rest_error.Error)
		}
	}

	return r0, r1
}

// Team_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type Team_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - id int
func (_e *Team_Expecter) GetById(id interface{}) *Team_GetById_Call {
	return &Team_GetById_Call{Call: _e.mock.On("GetById", id)}
}

func (_c *Team_GetById_Call) Run(run func(id int)) *Team_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *Team_GetById_Call) Return(_a0 *model.Team, _a1 *rest_error.Error) *Team_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Team_GetById_Call) RunAndReturn(run func(int) (*model.Team, *rest_error.Error)) *Team_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByParams provides a mock function with given fields: params
func (_m *Team) GetByParams(params model.TeamParams) ([]model.Team, *rest_error.Error) {
	ret := _m.Called(params)

	var r0 []model.Team
	var r1 *rest_error.Error
	if rf, ok := ret.Get(0).(func(model.TeamParams) ([]model.Team, *rest_error.Error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(model.TeamParams) []model.Team); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(model.TeamParams) *rest_error.Error); ok {
		r1 = rf(params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*rest_error.Error)
		}
	}

	return r0, r1
}

// Team_GetByParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByParams'
type Team_GetByParams_Call struct {
	*mock.Call
}

// GetByParams is a helper method to define mock.On call
//   - params model.TeamParams
func (_e *Team_Expecter) GetByParams(params interface{}) *Team_GetByParams_Call {
	return &Team_GetByParams_Call{Call: _e.mock.On("GetByParams", params)}
}

func (_c *Team_GetByParams_Call) Run(run func(params model.TeamParams)) *Team_GetByParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TeamParams))
	})
	return _c
}

func (_c *Team_GetByParams_Call) Return(_a0 []model.Team, _a1 *rest_error.Error) *Team_GetByParams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Team_GetByParams_Call) RunAndReturn(run func(model.TeamParams) ([]model.Team, *rest_error.Error)) *Team_GetByParams_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewTeam interface {
	mock.TestingT
	Cleanup(func())
}

// NewTeam creates a new instance of Team. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTeam(t mockConstructorTestingTNewTeam) *Team {
	mock := &Team{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
